kind: pipeline
type: docker
name: amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build & test
    image: rust:1.52
    environment:
      SQLX_OFFLINE: "true"
    commands:
      - cargo test --workspace --verbose

  - name: publish Docker image
    image: plugins/docker:18
    settings:
      auto_tag: true
      auto_tag_suffix: linux-amd64
      dockerfile: ./Dockerfile
      repo: sandhead/tumblepub
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
    when:
      branch:
        - main
      event:
        - push
        - tag

---
kind: pipeline
type: docker
name: arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: build & test
    image: rust:1.52
    environment:
      SQLX_OFFLINE: "true"
    commands:
      - cargo test --workspace --verbose

  - name: publish Docker image
    image: plugins/docker:18
    settings:
      auto_tag: true
      auto_tag_suffix: linux-arm64
      dockerfile: ./Dockerfile
      repo: sandhead/tumblepub
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
    when:
      branch:
        - main
      event:
        - push
        - tag