[package]
name = "bloq"
version = "0.1.0"
authors = ["Justin Schweigert <justin@schweigert.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
activitystreams = "0.6"
actix-files = "0.5"
actix-web = "3"
chrono = { version = "0.4", features = ["serde"] }
diesel = { version = "1.4", features = ["postgres", "chrono", "r2d2"] }
diesel_migrations = { version = "1.4", features = ["postgres"] }
dotenv = "0.15"
handlebars = "3.5"
juniper = "0.15"
lazy_static = "1.4"
percent-encoding = "2.1"
regex = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio-postgres = "0.7"