# if you're looking for the main binary, check the "tumblepub" directory

[workspace]
members = [
    "crates/activitypub",
    "crates/events",
    "crates/graphql",
    "crates/utils",
    "tumblepub"
]