[package]
name = "schweigert-dev"
version = "0.1.0"
authors = ["Justin Schweigert <justin@schweigert.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
activitystreams = "0.6.2"
actix-web = "3"
diesel = { version = "1.4.5", features = ["postgres", "r2d2"] }
diesel_migrations = { version = "1.4.0", features = ["postgres"] }
dotenv = "0.15.0"
handlebars = "3.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"