[package]
name = "bloq"
version = "0.1.0"
authors = ["Justin Schweigert <justin@schweigert.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# misc:
anyhow = "1.0"
async-trait = "0.1.47"
chrono = { version = "0.4", features = ["serde"] }
dotenv = "0.15"
thiserror = "1.0"
url = "2.2"
uuid = { version = "0.8", features = ["serde", "v4"] }
# web server:
actix-files = "0.5"
actix-web = "3"
juniper_actix = "0.2"
# database:
sqlx = { version = "0.4", features = ["runtime-actix-rustls", "postgres", "uuid", "chrono", "migrate"] }
# GraphQL:
juniper = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# ActivityPub:
activitystreams = "0.6"
lazy_static = "1.4"
regex = "1.4"
# theming:
handlebars = "3.5"
percent-encoding = "2.1"