# this docker-compose file contains dependencies used in development
# for now, it's just the postgres database, for SQLx
version: "3"
services:
  database:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
#    volumes:
#      - ./create_db.sh:/docker-entrypoint-initdb.d/20-create_db.sh
    environment:
      POSTGRES_PASSWORD: mysecretpassword