version: '3.4'

services:
  tumblepub:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  database:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
