name: CI/CD

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
    paths:
      - '.github/workflows/docker-publish.yml'
      - 'theme/**'
      - 'Tumblepub*/**'
      - '!theme/webpack.serve.js'
      - '!**/README.md'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/docker-publish.yml'
      - 'theme/**'
      - 'Tumblepub*/**'
      - '!theme/webpack.serve.js'
      - '!**/README.md'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Restore dependencies
      run: dotnet restore Tumblepub.sln
    - name: Build
      run: dotnet build --no-restore Tumblepub.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal Tumblepub.sln

  push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
    - uses: actions/checkout@v2
    - name: Configure Docker metadata
      id: metadata
      uses: docker/metadata-action@v3
      with:
        images: |
          ${{ secrets.DOCKERHUB_USERNAME }}/tumblepub
          ghcr.io/${{ github.repository_owner }}/tumblepub
        tags: |
          type=edge,branch=main
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log into Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Log into GitHub Container Repository
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: Build & push image
      uses: docker/build-push-action@v2
      with:
        push: true
        file: ./Tumblepub/Dockerfile
        context: ./
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.metadata.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
